### ISSUE TITLE
Where is the playlist saved?

### ISSUE THREAD

**Issue by acagastya** [deniszholob/playlist-maker#1]
Hi, I was trying out this tool, trying to save a playlist.  I tried on both demo and on local machine (by `npm start`), opened the songs and tried saving.  While I get an alert saying it was saved, I am not sure where exactly is it saved.  There is nothing in the console either.  Any clue where I should be looking?

**Comment by acagastya** [comment]
I might have been using it wrong, perhaps?  I did `npm start` and `npm run start:electron` and the electron application seems to be saving it just fine.  Though I am not sure how you intend it to be used.

**Comment by deniszholob** [comment]
Oh good point, ill add a path to where its saved in the notification!

In the web versions, you cant really save right now, but ill see if i can make it download a file instead, its a TODO item.
On the native/electron version, it will save over the opened playlist or whatever the new playlist location you selected.

Thanks for checking it out :)

**Comment by acagastya** [comment]
Really appreciate that, thanks!

**Comment by deniszholob** [comment]
Using alerts for now but, now the web version asks for a filename for new playlist and then displays it for the save
![image](https://user-images.githubusercontent.com/3830741/141587736-2a7aa921-dee1-46fd-a9ed-72d4dcee4e23.png)
![image](https://user-images.githubusercontent.com/3830741/141586107-7e3aa7b7-1301-4ccc-bd97-89e9f2fecf26.png)
