### ISSUE TITLE
[Feat req] UTF8 (m3u8) and FLAC support

### ISSUE THREAD

**Issue by acagastya** [deniszholob/playlist-maker#2]
There are two points I want to raise:

1. If I understand correctly m3u8 handles UTF-8, which can come handy for song titles like "Voilà" or non latin-names to be rendered properly.  If it it not too much, can a default m3u8 support be added?
2. I have all the flac songs, and as of now, mp3, wav, and ogg are the only ones supported.  https://github.com/deniszholob/playlist-maker/blob/2c2327637e367ddfb5e322f54007fee50f31e01f/libs/util/src/data/files.const.ts#L11 While I can add option for flac, maybe adding flac, m4a, aac and other majorly used formats too?

**Comment by deniszholob** [comment]
1. Should support .m3u8 by default actually!
https://github.com/deniszholob/playlist-maker/blob/2c2327637e367ddfb5e322f54007fee50f31e01f/libs/util/src/data/files.const.ts#L6
https://github.com/deniszholob/playlist-maker/blob/2c2327637e367ddfb5e322f54007fee50f31e01f/apps/electron/src/app/events/ElectronEventHandler.ts#L32
 
2. Yeah,  added the common ones to start, i might just do something like
```html
<input type="file" accept="audio/*">
```
in the html. I'll have to see about electron though
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#unique_file_type_specifiers

Also i created a project board with all the planned features: https://github.com/deniszholob/playlist-maker/projects/1
